---
title: "CPF Site Maps"
author: "Sam Struthers"
format: html
editor: visual
---

```{r setup, include=FALSE}
source("package_loader.R")
```

## Import datasets

```{r}
#buffer/watershed bs
buffer_sbs <- read_csv('data/sbs_buffer.csv') %>%
  mutate(Buffer_Level=((Unburned*0)+(V_Low*0.1)+(Low*0.4)+(Moderate*0.7)+(High*1))/(Unburned+V_Low+Low+Moderate+High))

watershed_sbs <- read_csv('data/sbs_watershed.csv') %>%
  mutate(Watershed_Level=((Unburned*0)+(V_Low*0.1)+(Low*0.4)+(Moderate*0.7)+(High*1))/(Unburned+V_Low+Low+Moderate+High))

dist_from_pbd <- read.csv('data/Distance_from_PBD.csv')

# Cameron Peak fire sites
CPF_sites <- read_csv('data/cpf_sites.csv' ) %>%
  mutate( x= Long, 
          y= Lat)%>%
  st_as_sf(coords=c("Long","Lat"), crs=4326)%>%
  mutate(watershed=ifelse(site_code %in% c('LNGR','LNGO'),"Long Draw Reservoir",
                   ifelse(site_code %in% c('PTRO','PTRR'),'Peterson Reservoir',
                   ifelse(site_code %in% c('SLEP','JWC','PNF','PBD', 'PJW','PBR', 'SFM','PSF' ),'CLP Mainstem Canyon',
                   ifelse(site_code %in% c('ELC','ARCH', 'LEGC','TIMB' ),'CLP Mainstem Fort Collins',
                   ifelse(site_code %in% c('JOEI','JOER'),"Joe Wright Reservoir",
                   ifelse(site_code %in% c('CBRI', 'CBRR','CHD'), "Chambers Reservoir",
                   ifelse(site_code %in% c('BRNR','BMD'),"Barnes Meadow Reservoir",
                   ifelse(site_code %in% c('COMR','COMO','COMI'),"Comanche Reservoir",
                          ifelse(site_code %in% c('HORO','HORI','HORR'),"Hourglass Reservoir","CLP Tributary" ))))))))))%>%
  left_join(dplyr::select(buffer_sbs,c(watershed,Buffer_Level)),by="watershed") %>%
  left_join(dplyr::select(watershed_sbs,c(site_code,Watershed_Level)),by="site_code")%>%
  left_join(dplyr::select(dist_from_pbd,c(site_code,distance_upstream_km)),by="site_code")%>%
   mutate(site_type=ifelse(Type %in% c('Outflow','Inflow'),"Stream",
                   ifelse(Type %in% c("Stream"),'Tributary',
                    ifelse(Type %in% c("Mainstem"),'Mainstem',"Reservoir"))))

CPF_sites$site_type = factor(CPF_sites$site_type, levels = c("Stream", "Reservoir", "Tributary", "Mainstem"))
#Cameron Peak fire outline
cpf_boundary <- st_read("data/cpf_sbs/cpf_boundary.shp")
#buffer+burn severity values
reservoir_map <- CPF_sites%>%
  filter(Campaign %in% c( "Chambers Complex", "Longdraw"))

#nhdplus waterbodies
clp <- get_huc8(id = '10190007')
clp_waterbodies <- get_waterbodies(AOI = clp)
cpf_waterbodies <- filter(clp_waterbodies, gnis_name %in% c("Chambers Lake", "Peterson Lake", "Barnes Meadow Reservoir","Long Draw Reservoir", "Joe Wright Reservoir", "Comanche Reservoir", "Hourglass Reservoir"))

chambers_lake <- filter(cpf_waterbodies, gnis_name == "Chambers Lake")
st_write(chambers_lake, "data/cpf_sbs/cpf_waterbodies/chambers_lake.shp")
peterson_lake <- filter(cpf_waterbodies, gnis_name == "Peterson Lake")
st_write(peterson_lake, "data/cpf_sbs/cpf_waterbodies/peterson_lake.shp")
long_draw_reservoir <- filter(cpf_waterbodies, gnis_name == "Long Draw Reservoir")
st_write(long_draw_reservoir, "data/cpf_sbs/cpf_waterbodies/long_draw_reservoir.shp")
barnes_meadow_reservoir <- filter(cpf_waterbodies, gnis_name == "Barnes Meadow Reservoir")
st_write(barnes_meadow_reservoir, "data/cpf_sbs/cpf_waterbodies/barnes_meadow.shp")
comanche_reservoir <-filter(cpf_waterbodies, gnis_name == "Comanche Reservoir")
st_write(comanche_reservoir, "data/cpf_sbs/cpf_waterbodies/comanche_reservoir.shp")
hourglass_reservoir <-filter(cpf_waterbodies, gnis_name == "Hourglass Reservoir")
st_write(hourglass_reservoir, "data/cpf_sbs/cpf_waterbodies/hourglass_reservoirs.shp")

clp_flowlines <- get_nhdplus(AOI = clp, 
                             realization='flowline')


bigT <- get_huc8(id = '10190006')
UpLaramie <- get_huc8(id ='10180010')

bigT_flowlines <- get_nhdplus(AOI = bigT, realization = 'flowline')

UpLaramie_flowlines <- get_nhdplus(AOI = UpLaramie, realization = 'flowline')


#Map boundaries 


#Chambers Map
#chambers_bound <- st_read("data/cpf_sbs/chambers_map.kml")
sf_res_bound <- st_read("data/cpf_sbs/sf_res_bound.kml")



st_write(CPF_sites, "data/cpf_sites.shp")

st_write(cpf_waterbodies, "data/cpf_waterbodies.shp")
st_write(clp_flowlines, "data/clp_flowlines.shp")
st_write(clp_waterbodies, "data/clp_waterbodies.shp")
st_write(bigT_flowlines, "data/bigT_flowlines.shp")
st_write(UpLaramie_flowlines, "data/upLaramie_flowlines.shp")

```

# Overview Map

```{r, echo=F }
mapview(cpf_waterbodies)

mapview(CPF_sites,zcol='Campaign')+ mapview(cpf_boundary)
```

# Chlorophyll-a Analysis

```{r}
CPF_sites <- CPF_sites %>% filter(Campaign!= "Dropped")
mapview(filter(CPF_sites,is.na(Chla)),col.regions="grey", layer.name="None") + mapview(filter(CPF_sites,!is.na(Chla)),zcol="Grab_Frequency", layer.name="Frequency") 
```

# Sensor Locations

```{r}
mapview(filter(CPF_sites, !Site_Acronym %in% c("PBR") & is.na(Isco) & is.na(DO) & is.na(Sonde)), col.regions="grey", layer.name="None") +
  mapview(filter(CPF_sites,!is.na(DO)), col.regions="Blue", layer.name="miniDOT") +
  mapview(filter(CPF_sites,!is.na(Sonde)), col.regions="Yellow", layer.name="AquaTROLL Sonde") +
  mapview(filter(CPF_sites, Site_Acronym %in% c("PBR")), col.regions="Orange", layer.name="FCW Sonde") +
  mapview(filter(CPF_sites,!is.na(Isco)), col.regions="Red", layer.name="Isco")
```

# Flow Data Locations

```{r}
mapview(filter(CPF_sites, !Site_Acronym %in% c("SFM","PBR") & is.na(Caprod)), col.regions="grey", layer.name="None") +
  mapview(filter(CPF_sites,!is.na(Caprod)), col.regions="Orange", layer.name="Caprod") +
  mapview(filter(CPF_sites, Site_Acronym %in% c("SFM","PBR")), col.regions="Yellow", layer.name="FCW PT Location") +
  mapview(filter(CPF_sites, !is.na(Sonde)), col.regions="Pink", layer.name="AquaTROLL Sonde")
```

# Funder Report Maps

```{r}

cpf_map_reservoirs <- ggplot(reservoir_map) +
  theme_void() +
  geom_sf_pattern(data=cpf_boundary, alpha=0.25,
                  pattern = 'circle', 
                  pattern_color = "Red", 
                  pattern_spacing = 0.03, 
                  pattern_density = 0.5,
                  pattern_angle   = 30,
                  outline.type    = 'legacy')+
  geom_sf(data = clp_flowlines, color = "#0072B2", size = 1.5)+
  geom_sf(data = clp_waterbodies, fill = "#88CCEE", alpha= .5)+
  geom_sf(data= cpf_waterbodies, fill = "#56B4E9")+
   geom_sf( aes(shape = Type),color = "black",  fill= "Black", size = 5)+
  geom_label_repel(aes(label = site_code, x= x, y=y ))+
   coord_sf(xlim = c(-105.7645, -105.9117), ylim=c(40.485, 40.62))+
  # geom_sf_label(aes(label = site_code, fill = Watershed_Level), color = "black",
  #               nudge_x = -.0005, nudge_y = -.0005, check_overlap= T)+
  scale_color_gradient2(name="Contributing Area Burn Intensity",low="#56B4E9", mid="#F0E442", high="#D55E00", guide="colourbar", midpoint=0.225, limits=c(0,0.45576),)+
  scale_fill_gradient2(name="Contributing Area Burn Intensity",low="#56B4E9", mid="#F0E442", high="#D55E00", guide="colourbar", midpoint=0.225, limits=c(0,0.45576),)+
  theme(legend.position="none",
  plot.title=element_text(hjust=0, vjust= 0)) +
   guides(fill=FALSE, color=FALSE) 


  plot(cpf_map_reservoirs)
  ggsave("output/main_res_map_draft1.jpg", height = 11, width = 8)

#cpf_test_map <- ggplot(cpf_boundary)+
 # geom_sf_pattern(pattern = 'placeholder', pattern_type = 'kitten')

#plot(cpf_test_map)

#ggsave("output/kitten_cpf.jpg", width = 11, height = 8)
  
  
```

## South Fork system map

```{r}
sf_res_sites <- CPF_sites %>%
  filter(Campaign == "South Fork"| site_code %in% c("PENN", "FISH"))


south_fork_map <- ggplot(sf_res_sites) +
  theme_void() +
  geom_sf_pattern(data=cpf_boundary, alpha=0.25,
                  pattern_type = 'hexagonal', 
                  pattern_color = "#D55E00",
                  pattern_fill = "#D55E00",
                  pattern_spacing = 0.0002, 
                  pattern_density = .75,
                  pattern_angle   = 30)+
  geom_sf(data = clp_flowlines, color = "#0072B2", size = 4)+
  geom_sf(data = clp_waterbodies, fill = "#88CCEE", alpha= .5)+
  geom_sf(data= cpf_waterbodies, fill = "#56B4E9")+
   geom_sf( aes(shape = Type),color = "black",  fill= "Black", size = 5)+
  scale_shape_manual(values = c(17, 19, 16, 15, 23 ))+
  geom_label_repel(aes(label = site_code, x= x, y=y ))+
   coord_sf(xlim = c(-105.6698, -105.5109), ylim=c(40.56019, 40.62179))+
  scale_color_gradient2(name="Contributing Area Burn Intensity",low="#56B4E9", mid="#F0E442", high="#D55E00", guide="colourbar", midpoint=0.225, limits=c(0,0.45576),)+
  scale_fill_gradient2(name="Contributing Area Burn Intensity",low="#56B4E9", mid="#F0E442", high="#D55E00", guide="colourbar", midpoint=0.225, limits=c(0,0.45576),)+
  theme(legend.position="none",
  plot.title=element_text(hjust=0, vjust= 0)) +
   guides(fill=FALSE, color=FALSE) 


  plot(south_fork_map)
  ggsave("output/sf_res_map_draft1.jpg", height = 8, width = 12)


```

CPRW Sites

```{r}
folder_path <-"~/Documents/fork_yeah/cameron_peak_fire_study/data/spatial"

file_names <- tibble(file_name  = list.files(folder_path, 
                                recursive = TRUE, 
                                full.names = TRUE))%>%
  filter(grepl(".shp",file_name)&!grepl("xml",file_name))%>%
  pull()

prelim_2023_sites <- st_read(file_names[1])
cdphe_2021 <- st_read(file_names[2])
cdphe_2022 <- st_read(file_names[3])
cherokee_park <-  st_read(file_names[4])
elkhorn_crk  <- st_read(file_names[5])
red_feather <- st_read(file_names[6])

mapview::mapview(prelim_2023_sites, col.regions = "red")+
mapview::mapview(cdphe_2021, col.regions = "cyan")+
  mapview::mapview(cdphe_2022, col.regions = "purple")+
  mapview::mapview(cherokee_park, col.regions = "blue")+
  mapview::mapview(elkhorn_crk, col.regions = "orange")+
  mapview::mapview(red_feather, col.regions = "green")+
  mapview::mapview(CPF_sites, col.regions = "white", cex = "6")

```
