---
title: "Longitudinal mapping of Reservoir -> River Connection"
author: "Sam Struthers"
format: html
editor: visual
self-contained: true
---

## Goals

This document is to work on graphs related to nutrients from Reservoirs/ mainstem

### Importing

Loading packages and creating lists of sites based on location/grouping

```{r}
source("package_loader.R")
source("field_chemistry/00_colors_and_groups.R")


reservoir_chemistry <- read_feather("data/field_chemistry/cleaned/reservoir_chem_2021_2022.feather")%>%
  mutate(location = factor(location, levels = c("Inflow","Reservoir", "Outflow", "Stream", "Mainstem")))



```

## Data frame creation

```{r}


res_2021 <- filter(reservoir_chemistry, site_code %in% jw_chambers_complex & Year == 2021)

# filter reservoir chemistry for 2022
# only use sites from all_res_system and mainstem_sites

all_system_2022 <- filter(reservoir_chemistry, site_code %in% c(all_res_system, mainstem_sites, "BEAV") & 
                            Year == 2022)


```

## Functionalize pivoting for var

```{r}

nutrient = "ChlA"

get_ratios_2022 <- function(nutrient){
}
  
  nr <- all_system_2022%>%
    dplyr::select(date = Date,
         site_code,
         all_of(nutrient))%>%
  pivot_wider(names_from = site_code, values_from = nutrient)%>%
    filter(date %nin% genomic_dates)
  ## Remove rows were all columns other than Date are NA
 nr_no_na_rows <- nr[rowSums(is.na(nr)) != (ncol(nr)-1), ]%>%
   thicken(interval = "week", 
           start_val = as.Date("2022-05-30"))
# remove the date column and consolidate the rows by date_week
  nr_concise <- nr_no_na_rows%>%
    select(-date)%>%
    pivot_longer(cols = c(-date_week), 
                 names_to = "site",
                 values_to = "value")%>%
    drop_na()%>%
  pivot_wider(names_from = site, values_from = value)
  

    
  nr_final_df <- nr_concise%>%
    mutate(JOEI_JOER  = (JOEI/JOER)*100, 
           JOER_CBRI = (JOER/CBRI)*100, 
           CBRI_CBRR = (CBRI/CBRR)*100, 
           CBRR_CHD = (CBRR/CHD)*100, 
           CHD_JWC = (CHD/JWC)*100, 
           BRNR_BMD = (BRNR/BMD)*100, 
           BMD_JWC = (BMD/JWC)*100, 
           PTRR_PTRO = (PTRR/PTRO)*100, 
           PTRO_PJW = (PTRO/PJW)*100, 
           LNGR_LNGO = (LNGR/LNGO)*100, 
           LNGO_PJW = (LNGO/PJW)*100, 
           JWC_SLEP = (JWC/SLEP)*100,
           PJW_SLEP = (PJW/SLEP)*100, 
           SLEP_PBR = (SLEP/PBR)*100, 
           PBR_PSF = (PBR/PSF)*100, 
           COMI_COMR = (COMI/COMR)*100, 
           COMR_COMO = (COMR/COMO)*100, 
           COMO_BEAV =  (COMO/BEAV)*100 , 
           HORI_HORR = (HORI/HORR)*100, 
           HORR_HORO = (HORR/HORO)*100, 
           HORO_BEAV = (HORO/BEAV)*100, 
           BEAV_SFM = (BEAV/SFM)*100, 
           SFM_PSF = (SFM/PSF)*100, 
           PSF_PNF = (PSF/PNF)*100, 
           PNF_PBD = (PNF/PBD)*100
           )%>%
    pivot_longer(., cols = -date_week, names_to = "site_code", values_to = nutrient)
  


```
### Set up spatial data

```{r}

  up_and_down_sites <- nr_final_df %>%
  distinct(site_code) %>%
  filter(site_code %nin% c(all_res_system, mainstem_sites, "BEAV")) %>%
  mutate(site_one= str_extract(site_code, "^[A-Z]+"),
         site_two = str_extract(site_code, "[A-Z]+$"),
         site_ratio = site_code) %>%
  left_join(Sites, by = c("site_one" = "site_code")) %>%
  dplyr::rename(lat1 = Lat, long1 = Long) %>%
  left_join(Sites, by = c("site_two" = "site_code")) %>%
  dplyr::rename(lat2 = Lat, long2 = Long) %>%
  select(site_ratio, lat1, long1, lat2, long2)

up_site_lines <- select(up_and_down_sites, site_ratio, Long = long1, Lat = lat1)%>%
  st_as_sf(coords = c("Long", "Lat"), crs = 4326)
down_site_lines <- select(up_and_down_sites, site_ratio, Long = long2, Lat = lat2)%>%
  st_as_sf(coords = c("Long", "Lat"), crs = 4326)

site_lines <-st_union(up_site_lines, down_site_lines)%>%
  filter(site_ratio == site_ratio.1)%>%
  st_cast(to = "LINESTRING")%>%
  dplyr::select(site_code = site_ratio, geometry)


site_points <- Sites%>%
  dplyr::select(site_code, Lat, Long)%>%
  filter(site_code %in% c(all_res_system, mainstem_sites, "BEAV"))%>%
  st_as_sf(coords = c("Long", "Lat"), crs = 4326)
```


### Join ratio and spatial
```{r}


nutrient_ratios_lines <- nr_final_df %>%
  inner_join(site_lines, by = "site_code")%>%
  st_sf()%>%
  dplyr::rename(percent_change = ChlA )




nutrient_ratios_points <- nr_final_df %>%
  inner_join(site_points, by = "site_code")%>%
  st_sf()



```


## Plot

```{r}

tester <- tm_shape(nutrient_ratios_points, name = "Sampling Locations")+
  tm_bubbles(size = "ChlA")+
  tm_shape(nutrient_ratios_lines, name = "Sampling Locations")+
  tm_lines(size = "percent_change")+
  tm_facets(along = "date_week", free.coords = FALSE, free.scales.symbol.size = FALSE,
            nrow = 1, ncol = 1)




tester
tester_lines
tmap_animation(tester, filename = "output/spatial/chla_tester_points.gif", width = 1200, height = 600, delay = 15)
tmap_animation(tester_lines, filename = "output/spatial/chla_tester_lines.gif", width = 1200, height = 600, delay = 15)

```





## Functionalize 2021 JOER/CBRR dataset

```{r}


plot_long_jw_ch <- function(param, year = 2021,  title = FALSE){


  ratio_for_param <- filter(reservoir_chemistry, site_code %in% jw_chambers_complex & Year == year)%>%
    dplyr::select(all_of(param), Date, site_code)%>%
     pivot_wider(names_from = site_code, values_from = param)%>%
    drop_na()%>%
    mutate(JOEI_JOER = JOER/JOEI, 
           JOER_CBRI = CBRI/JOER,
           CBRI_CBRR = CBRR/CBRI,
           CBRR_CHD = CHD/CBRR)
  

  
# create a mean_2021 dataframe that has the mean of JOEI, JOER, CBRI, CBRR and CHD
#pivot longer and name the columns "site" and "value"
  mean_2021 <- ratio_for_param%>%
    pivot_longer(cols = c("JOEI", "JOER", "CBRI", "CBRR", "CHD"),
                 names_to = "site",
                 values_to = "value")%>%
    group_by(site)%>%
    summarise(mean = mean(value), 
              sd = sd(value))%>%
    ungroup()%>%
    mutate(site = factor(site, levels = c("JOEI", "JOER", "CBRI", "CBRR", "CHD")), 
           mean_plus_sd = mean + sd, 
           mean_minus_sd = mean - sd, 
           type = "mean")
  
  no_ratios_2021 <- ratio_for_param%>%
    pivot_longer(cols = c("JOEI", "JOER", "CBRI", "CBRR", "CHD"),
                 names_to = "site",
                 values_to = "value")%>%
     mutate(site = factor(site, levels = c("JOEI", "JOER", "CBRI", "CBRR", "CHD")))

 if(title == TRUE){
 plot <- ggplot(mean_2021, aes(x = site))+
   geom_point(data = no_ratios_2021, aes(y = value, color = site), alpha  = .6)+
   geom_ribbon(aes(ymin = mean_minus_sd, ymax = mean_plus_sd, 
                  group = type), alpha = 0.2)+
   geom_point(aes(y = mean))+
   geom_line(aes( y = mean, group = type))+
   scale_color_manual(values = colorsBS_in_order)+
   theme_few(base_size = 20) +
   labs(x = "Site (Upstream to Downstream)", 
        y = param)+
   #add the year in the top left quadrant of the plot
    annotate("text", x = 1, y = 1.5, label = year, size = 10)+
    theme(legend.position = "none")
}
  
  if(title == FALSE){
 plot <- ggplot(mean_2021, aes(x = site))+
   geom_point(data = no_ratios_2021, aes(y = value, color = site), alpha  = .6)+
   geom_ribbon(aes(ymin = mean_minus_sd, ymax = mean_plus_sd, 
                  group = type), alpha = 0.2)+
   geom_point(aes(y = mean))+
   geom_line(aes( y = mean, group = type))+
   scale_color_manual(values = colorsBS_in_order)+
   theme_few(base_size = 20) +
   labs(x = "Site (Upstream to Downstream)", 
        y = param)+
        
        #remove x axis labels and title
      theme(axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            axis.title.x = element_blank())+
    theme(legend.position = "none")
}
 return(plot)
}
```

## Param long 2021 JW CH plots

```{r}
# run the function for each parameter: ChlA, NO3, PO4, NH4, DOC, DTN, pH, SO4, K
# save each plot as a variable

no3 <- plot_long_jw_ch_2021(param = "NO3")
nh4 <- plot_long_jw_ch_2021(param = "NH4")
doc <- plot_long_jw_ch_2021(param = "DOC")
dtn <- plot_long_jw_ch_2021(param = "DTN")
ph <- plot_long_jw_ch_2021(param = "pH")
so4 <- plot_long_jw_ch_2021(param = "SO4")
k <- plot_long_jw_ch_2021(param = "K", title = TRUE)
chlA <- plot_long_jw_ch_2021(param = "ChlA", title = TRUE)
tss <- plot_long_jw_ch_2021(param = "TSS")
turbidity <- plot_long_jw_ch_2021(param = "Turbidity", title = TRUE)

#arrange the plots in a grid
ggarrange(no3, nh4, doc, dtn, ph, so4, k, chlA, ncol = 2, nrow = 4)



no3_2021 <- plot_long_jw_ch(param = "NO3", year = 2021)
no3_2022 <- plot_long_jw_ch(param = "NO3", year = 2022, title = TRUE)
chla_2021 <- plot_long_jw_ch(param = "ChlA", year = 2021)
chla_2022 <- plot_long_jw_ch(param = "ChlA", year = 2022, title = TRUE)

ggarrange(chla_2021, no3_2021, chla_2022, no3_2022, ncol = 2, nrow = 2)
ggsave("output/chla_no3_JW_CH_facet_mean_sd.jpg", width = 24, height = 16, dpi = 300)
```





